# version: '3.8'
# SQLiteを使用する場合、MySQLサービス (db サービス) は不要です。ここでは削除！
services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /Users/user1/Desktop/vite-project/database:/var/www/html/database # SQLiteのデータベースファイルをマウント
    ports:
      - 8000:8000
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: vite_nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80" # ポート番号を 8080 に変更
    networks:
      - laravel
    depends_on:
      - app

# SQLite用にデータベースファイルを指定
volumes:
  # SQLiteのデータベースを格納するボリューム設定
  sqlite_data:

networks:
  laravel:
